name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check code style
      run: npm run lint

    - name: Run unit tests
      run: npm run test:unit
      env:
        REACT_APP_HOLIDAY_API_BASE_URL: ${{ secrets.HOLIDAY_API_BASE_URL }}
        REACT_APP_HOLIDAY_API_KEY: ${{ secrets.HOLIDAY_API_KEY }}

    - name: Run integration tests
      run: npm run test:integration
      env:
        REACT_APP_HOLIDAY_API_BASE_URL: ${{ secrets.HOLIDAY_API_BASE_URL }}
        REACT_APP_HOLIDAY_API_KEY: ${{ secrets.HOLIDAY_API_KEY }}

    - name: Build project
      run: npm run build
      env:
        REACT_APP_HOLIDAY_API_BASE_URL: ${{ secrets.HOLIDAY_API_BASE_URL }}
        REACT_APP_HOLIDAY_API_KEY: ${{ secrets.HOLIDAY_API_KEY }}

    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage/

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/